### PR TITLE
update to Release_2016_03_4

### PR DESCRIPTION
**Pull request by rvianello**
updates the rdkit and rdkit-postgres* recipes to build the current patch release.

### CODE REVIEW

**Comment by rvianello** [comment]
Thank you, I uploaded some up-to-date linux packages to the anaconda channel.

**Comment by greglandrum** [comment]
Thanks Riccardo. I'll try to get a Mac package up soon too

**Comment by greglandrum** [comment]
@rvianello : the linux builds were done without cairo support. Was this intentional or an oversight?

**Comment by rvianello** [comment]
this is unexpected, the changes in the rdkit recipe are limited to the git tag. I'll look into this.

**Comment by greglandrum** [comment]
I probably have confused myself. It may be that the linux builds never included cairo support for the C++ rendering code
Since we're including cairocffi as a build dependency (should also be a run dependency?), it seems like we assume that cairo will be on the system. If that's the case, couldn't we safely add `-D RDK_BUILD_CAIRO_SUPPORT=ON` to the build arguments?

**Comment by rvianello** [comment]
cairo/cairocffi were not included as runtime dependencies just to avoid the mandatory installation of the graphics stack when not used, but on linux I think cairo may be safely assumed to be available, and yes, I agree it should be possible to add the RDK_BUILD_CAIRO_SUPPORT settings to the cmake command line. I will test this on a branch and then create a PR.

**Pull request merged**
