### PR TITLE
fix unix boost version to 1.65.1

### PR DESCRIPTION
**Pull request by markussitzmann**
fix unix boost version to 1.65.1 in boost/meta.yaml

### CODE REVIEW

**Comment by markussitzmann** [comment]
The following of my Docker scripts (if you replace line 45-47 with 'rdkit/conda-rdkit' instead of my fork and checkout branch 'development'):

https://github.com/chembience/chembience/blob/master/context/base/rdkit/Dockerfile

created a RDKit version that was missing boost 1.65.1 and there was only (I think) boost 1.63 available. So, with my fork and the pushed fix I got it working again). Maybe I have to re-check it.

**Comment by greglandrum** [comment]
Please give it a try again. Note that there were some fairly major changes to the way the build is done when we switched to the new anaconda5 setup with #64 
This docker image shows a build process that works for me:
https://github.com/rdkit/rdkit_containers/blob/master/docker/centos6_anaconda5/Dockerfile

(I'm currently running that again now to confirm that it still works, I will update this comment if it does not).

**Comment by greglandrum** [comment]
@markussitzmann : does the new version of the development branch work for you now?

**Comment by markussitzmann** [comment]
Hi Greg,
sorry for the late reply - I had it working since then, however, the reason why I found your reply now is because I have trouble again with boost. I am currently investigating (I saw there are also some other recent issues with boost).

Markus

**Pull request closed without merging**
