### PR TITLE
Add a headless cairo build

### PR DESCRIPTION
**Pull request by greglandrum**
Adds a `cairo_nox` target that builds a minimal version of cairo without requiring GTK or X and makes building with Cairo support the default for the RDKit.

This still needs to be tested on and adapted for windows and the Mac.

### CODE REVIEW

**Comment by rvianello** [comment]
sorry about the very late comment. I think this should be definitely merged, but I'm a bit unclear about the interoperability of an rdkit package built with a dependency from cairo_nox when deployed in a regular environment where the cairo package from anaconda might be also installed. 

would it make sense to try to implement some kind of configuration switch in the rdkit recipe, so that it could be optionally built using either cairo_nox or cairo?

**Comment by greglandrum** [comment]
Is there a way to "or" dependencies in conda? It seems like the cairo_nox build should work with a standard cairo install.

**Comment by rvianello** [comment]
I don't think there is a way to specify that a dependency may be satisfied by either one package or the to other, but if the cairo_nox and the standard cairo packages provide equivalent api/abi then maybe we could define 'nox' as a package "feature" (http://conda.pydata.org/docs/building/meta-yaml.html#id1) and this way drive the dependency resolution to select the desired variant (for eample, features are the mechanism anaconda uses to toggle between the regular and mkl versions of the same packages). I need to test this, but I think in practice it could require a simple "nox" metapackage to help add/remove the feature from the environment, and the cairo_nox recipe should then be changed to produce a package with name "cairo", but also providing the "nox" feature

**Comment by greglandrum** [comment]
Closing this one because I think I have it fixed properly using features.
I'll re-open a new one.

**Pull request closed without merging**
