### PR TITLE
Add own cairo

### PR DESCRIPTION
**Pull request by greglandrum**

### CODE REVIEW

**Comment by rvianello** [comment]
nice. it worked pretty well for me on linux, at least when the 'nox' feature was added to a regular environment, and the desired variant of the cairo package was installed as well, replacing the one from the anaconda distribution. 

removing the feature wasn't as clean, 'conda remove --features nox' didn't find the package, and a plain 'conda remove nox' also removed cairo together with cairocffi and rdkit. Those packages were quick to install again, but the behavior was a bit unexpected. did it work better for you?

In any case, the changes look good to me, maybe cairo_nox could be added to the Dockerfile?

**Comment by greglandrum** [comment]
Here's what happens for me:
```
(py35_rdkit) [root@8fc2236116eb ~]# conda uninstall nox
Fetching package metadata .........
Solving package specifications: ..........

Package plan for package removal in environment /opt/conda/envs/py35_rdkit:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    rdkit-2016.09.2            |      np111py35_1        18.3 MB  rdkit

The following packages will be REMOVED:

    cairo: 1.14.6-nox_0          greglandrum [nox]
    nox:   1.0-0                 greglandrum

The following packages will be SUPERCEDED by a higher-priority channel:

    rdkit: 2016.09.2-np111py35_1 greglandrum --> 2016.09.2-np111py35_1 rdkit
```

I don't really understand the concept of features in conda, but this feels like the correct behavior: the cairo package I had installed was dependent on the nox feature and the rdkit was dependent on cairo, so uninstalling nox leads to uninstalling the rdkit and cairo.

**Comment by greglandrum** [comment]
@rvianello : while I'm editing the Dockerfile, do you have any objections to me removing the python 3.4 builds?

**Comment by rvianello** [comment]
@greglandrum no, I think removing the python 3.4 packages should be fine (especially for conda users), thank you.

Thanks for testing the removal workflow for the nox feature, that's exactly how I was expecting it to work, I think it may be related to my environment. I installed this version of rdkit and the nox packages from the local conda-build channel and I suspect it could make a difference.

**Comment by greglandrum** [comment]
I'm attempting the `docker build` now. I'll let you know how that goes.

**Comment by greglandrum** [comment]
@rvianello : I'm getting failures while trying to build postgresql:
```Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok

*failure*
Consult the last few lines of "pg_upgrade_server.log" for
the probable cause of the failure.

connection to database failed: Unix-domain socket path "/home/rdkit/miniconda/conda-bld/postgresql_1480090270736/work/postgresql-9.4.4/contrib/pg_upgrade/.s.PGSQL.57636" is too long (maximum 107 bytes)
```
have you seen this before?

**Comment by rvianello** [comment]
@greglandrum no, this specific error is new. If it's just due to the length of the build directory path (as denoted in the message) I should be able to work around it in a couple of ways (e.g. with some $CONDA_BLD_PATH settings relocating the build to a more suitable location).

thanks for adding eigen to the build

**Comment by greglandrum** [comment]
@rvianello : should we then merge this as is (since the primary rdkit stuff is, I believe, working) and you can try the postgresql build changes afterwards?

**Comment by rvianello** [comment]
yes, I think it would make sense, the features added by this PR seem to work fine, and the error looks like a side effect of how the build directories are handled by the more recent versions of conda-build, so the current master is unlikely to be exempt from that specific problem

**Pull request merged**
